homeassistant:
  # Name of the location where Home Assistant is running
  name: home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.738228
  longitude: 103.986067
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  #customize_glob:
  #  "*.*":
  #    custom_ui_state_card: state-card-custom-ui

  auth_providers:
    - type: homeassistant
   # uncomment this to enable backwards compatible API password support
    - type: legacy_api_password

  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages/

http:
  api_password: zxl1988
  ssl_certificate: /home/homeassistant/.homeassistant/ssl_key/server.crt
  ssl_key: /home/homeassistant/.homeassistant/ssl_key/private.key

# Show links to resources in log and frontend
introduction:

customizer:
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index
# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-weather.html
    - /local/custom_ui/state-card-custom-phicomm-aircat.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-weather.html
    - /local/custom_ui/state-card-custom-phicomm-aircat.html
# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:
# enable:
#  - dlna_dmr

#media_player:
#  - platform: dlna_dmr
#    url: http://192.168.0.10:9197/dmr

dlna:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

zone:
  name: office
  latitude: 30.767
  longitude: 103.909
  radius: 100
  icon: mdi:worker
 
#  name: home  
#  latitude: 30.738
#  longitude: 103.986
#  radius: 100
#  icon: mdi:home

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

aligenie:  
  expire_hours: 30

logger:
  default: info

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

