sensor:
  - platform: template
    sensors:
      m1_hcho:
        friendly_name: 卧室甲醛
        value_template: "{{ states.sensor.m1.attributes.hcho }}"
        unit_of_measurement: "mg/m³"
      m1_pm25:
        friendly_name: 卧室PM25
        value_template: "{{ states.sensor.m1.attributes.pm25 }}"
        unit_of_measurement: "µg/m³"
      m1_temp:
        friendly_name: 卧室温度
        value_template: "{{ states.sensor.m1.attributes.temperature }}"
        unit_of_measurement: "°C"
      m1_humid:
        friendly_name: 卧室湿度
        value_template: "{{ states.sensor.m1.attributes.humidity }}"
        unit_of_measurement: "%"