sensor:
  - platform: PhicommAirDetector
    name: m1
#phicommAccount : 18583269806
#phicommPassowrd: 18583269806
#airDetectorMac: "B0:F8:93:11:BE:23"
    
input_number:
  phicomm_m1_led:
    name: 屏幕亮度
    icon: mdi:led-on
    initial: 50
    min: 0
    max: 50
    step: 25

input_boolean:
  phicomm_m1_reset:
    name: Retry
    icon: mdi:lock-reset
    initial: False
      
group:
  m1:
    name: 空气检测仪M1
    view: no
    entities:
      - sensor.m1
      - input_number.phicomm_m1_led
      - input_boolean.phicomm_m1_reset


homeassistant:
  customize:
    sensor.m1:
      custom_ui_state_card: state-card-custom-phicomm-aircat



sensor:
  - platform: template
    sensors:
      m1_hcho:
        friendly_name: 卧室甲醛
        value_template: "{{ states.sensor.m1.attributes.hcho }}"
        unit_of_measurement: "mg/m³"
      m1_pm25:
        friendly_name: 卧室PM25
        value_template: "{{ states.sensor.m1.attributes.pm25 }}"
        unit_of_measurement: "µg/m³"
      m1_temp:
        friendly_name: 卧室温度
        value_template: "{{ states.sensor.m1.attributes.temperature }}"
        unit_of_measurement: "°C"
      m1_humid:
        friendly_name: 卧室湿度
        value_template: "{{ states.sensor.m1.attributes.humidity }}"
        unit_of_measurement: "%"