switch:
  - platform: phicomm_dc1
    name: dc1
    hidden: true
    mac: {'7-7250972876957364'}
   
sensor:
  - platform: template
    sensors:
      dc1_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_s0.attributes.V }}"
        unit_of_measurement: V
      dc1_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_s0.attributes.P }}"
        unit_of_measurement: W
     
group:
  dc1:
    name: DC1排插
    view: no
    entities:
      - sensor.dc1_v
      - sensor.dc1_p
      # - sensor.dc1_totale
      - switch.dc1_s0
      - switch.dc1_s1
      - switch.dc1_s2
      - switch.dc1_s3
 
homeassistant:        
  customize:
    # Add an entry for each entity that you want to overwrite.
    switch.dc1_s0:
      friendly_name: all
    switch.dc1_s1:
      friendly_name: 台灯
    switch.dc1_s2:
      friendly_name: 斐讯音箱
    switch.dc1_s3:
      friendly_name: 电脑和显示器

